yiisoft/yii-debug

src/Module.php
tests/ModuleTest.php

| Is bugfix?    | yes/no
| New feature?  | yes/no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
[yiisoft/view PR #1](https://github.com/yiisoft/view/pull/1) needs to be accepted first

fixed tests

---

src/models/search/Db.php
src/models/search/Event.php
src/models/search/Log.php
src/models/search/Mail.php
src/models/search/Profile.php
src/views/default/panels/mail/detail.php

fix errors to ensure normal operation

fix errors to ensure normal operation

---

.gitignore
.travis.yml
composer.json
src/Panel.php
src/models/timeline/Svg.php
src/panels/DbPanel.php
src/panels/UserPanel.php
src/views/default/panels/assets/detail.php
src/views/default/panels/timeline/detail.php

To be merged once yiisoft/inflector is published to packagist

Switch to external helpers

---

composer.json
config/tests.php
src/Panel.php
src/Panels/AssetPanel.php
src/Panels/ConfigPanel.php
src/Panels/DbPanel.php
src/Panels/DumpPanel.php
src/Panels/EventPanel.php
src/Panels/LogPanel.php
src/Panels/MailPanel.php
src/Panels/ProfilingPanel.php
src/Panels/RequestPanel.php
src/Panels/RouterPanel.php
src/Panels/TimelinePanel.php
src/Panels/UserPanel.php
src/TimelineAsset.php
tests/PanelTest.php

* Make it implement ViewContextInterface and its own render() method
* Remove the `$app` property from base class and use DI injection where possible

Refactor Panel

---

config/params.php
src/Collector/RouterCollector.php
tests/Collector/RouterCollectorTest.php

Added RouterCollector

---

README.md

Delete non-existent link

---

composer.json
config/common.php
config/params.php
src/Debugger.php
src/Storage/FileStorage.php
src/Storage/MemoryStorage.php
src/Storage/StorageInterface.php

Update to json data format, add filesystem

---

config/events.php
config/providers.php

Fix debugger config

---

config/events.php

Remove params check from events config

---

config/events-console.php
src/Collector/EventCollector.php
src/DebugServiceProvider.php
src/ProxyServiceProvider.php

Remove EventConfigurator, add console ApplicationStartup event check

---

config/common.php
config/console.php
config/events-console.php
config/events-web.php
config/params.php
config/providers.php
config/web.php

Update params format

---

config/events-web.php
config/params.php
src/Collector/RequestCollector.php
tests/Collector/RequestCollectorTest.php

Add request collector

---

config/common.php
src/Collector/EventCollectorInterface.php
src/Collector/IndexCollectorInterface.php
src/Collector/RequestCollector.php
src/Collector/WebAppInfoCollector.php
src/Storage/FileStorage.php

Add gc & index file generator

---

src/Storage/FileStorage.php

Use id instead of tag

---

config/params.php
config/web.php
src/Collector/CommandCollector.php
src/Collector/LogCollector.php
src/Collector/RequestCollector.php
src/Collector/ServiceCollector.php
src/Debugger.php

Ability skip collecting requests

---

src/Collector/WebAppInfoCollector.php

Add timestamp to index data

---

src/Collector/RouterCollector.php

Fix route collector

---

composer.json

| Fixed issues  | Fix composer deps

Add psalm to composer

---

src/DebuggerIdGenerator.php
src/Storage/FileStorage.php

| Fixed issues  | 
Now debug files will group by timestamp

Group resources by time

---

config/common.php

Ability to set historySize

---

src/Collector/RouterCollector.php

Change UrlMatcher to RouteCollection

---

.github/workflows/bc.yml_
.github/workflows/build.yml
.github/workflows/static.yml
config/console.php
config/web.php
src/Collector/CommandCollector.php
src/Collector/ConsoleAppInfoCollector.php

Improve console collectors & minor changes

---

.github/workflows/build.yml
.github/workflows/mutation.yml
.github/workflows/static.yml
README.md
composer.json
phpunit.xml.dist
tests/FlattenExceptionTest.php

Update dev dependencies, pipelines and README.md.

---

src/Collector/ConsoleAppInfoCollector.php
src/Collector/MiddlewareCollector.php
src/Collector/WebAppInfoCollector.php

Fix calculating memory usages.

---

config/events-web.php
src/Collector/MiddlewareCollector.php

| Fixed issues  | https://github.com/yiisoft/yii-web/pull/344

Use events from middleware-dispatcher

---

src/Collector/LogCollector.php
src/Collector/LogCollectorInterface.php
tests/Collector/WebAppInfoCollectorTest.php

| Fixed issues  | https://github.com/yiisoft/yii-demo/issues/187

Fix error when logging non-strings

---

config/params.php

Ignore /assets/* routes

---

src/FlattenException.php

Cleanup FlattenException

---

src/Storage/FileStorage.php

Reindex objects

---

config/events-web.php

| Fixed issues  | Fix for collect profiler logs

Flush profiler before shutdown for collect logs

---

src/Dumper.php
src/Storage/FileStorage.php
tests/DumperTest.php

| Fixed issues  | https://github.com/yiisoft/var-dumper/pull/38

Move dumper

---

src/Collector/CommandCollector.php

Fix CommandCollector

---

composer.json

Use stable version of yiisoft/var-dumper

---

config/params.php

Add Cache to services

---

config/common.php

Always provide storage interface definition

---

tests/Proxy/ContainerInterfaceProxyTest.php

Fix test for a message

---

README.md
tests/DebugServiceProviderTest.php
tests/ProxyServiceProviderTest.php

| Fixed issues  | https://github.com/yiisoft/factory/pull/78

Adopt factory

---

composer.json
config/common.php
src/Proxy/ContainerInterfaceProxy.php

Remove usage of container proxy interface

---

config/console.php
config/web.php
src/DebuggerIdGenerator.php
tests/Proxy/UrlMatcherInterfaceProxyTest.php

Adjust config

---

config/console.php
config/web.php

Adopt to `yiisoft/definitions`

---

.github/workflows/build.yml
.github/workflows/mutation.yml
.github/workflows/static.yml
composer.json
config/events-web.php
src/Collector/EventCollector.php
src/Collector/RequestCollector.php
src/Collector/WebAppInfoCollector.php
src/Debugger.php
tests/Collector/RequestCollectorTest.php
tests/Collector/WebAppInfoCollectorTest.php
tests/DebuggerTest.php

Waiting:
https://github.com/yiisoft/app/pull/209
https://github.com/yiisoft/demo/pull/389
https://github.com/yiisoft/demo-api/pull/63
https://github.com/yiisoft/app-api/pull/108

Replace usage of yii-web to yii-http, remove support PHP 7.4

---

tests/Collector/RouterCollectorTest.php
tests/DebugServiceProviderTest.php
tests/Proxy/ContainerInterfaceProxyTest.php
tests/ProxyServiceProviderTest.php

| Fixed issues  | https://github.com/yiisoft/di/pull/276

Adapt to DI changes

---

config/events-console.php
src/Collector/EventCollector.php
src/Collector/EventCollectorInterface.php
src/Collector/LogCollector.php
src/Collector/LogCollectorInterface.php
src/Collector/MiddlewareCollector.php
src/Proxy/EventDispatcherInterfaceProxy.php
src/Proxy/LoggerInterfaceProxy.php
src/Proxy/ProxyLogTrait.php
tests/Collector/EventCollectorTest.php
tests/Collector/LogCollectorTest.php
tests/Collector/MiddlewareCollectorTest.php
tests/Proxy/EventDispatcherProxyTest.php

- Collect event fired line
- Collect log written line
- Split action handler when collecting middleware stack

Enhancements

---

src/Collector/MiddlewareCollector.php

| Fixed issues  | Fixed collecting `afterStack`

Improve MiddlewareCollector

---

src/Collector/RequestCollector.php
tests/Collector/RequestCollectorTest.php

Improve request collector

---

config/events-web.php
config/params.php
src/Collector/AssetCollector.php
src/Collector/WebViewCollector.php
src/Proxy/AssetLoaderInterfaceProxy.php
tests/Collector/AssetCollectorTest.php
tests/Collector/WebViewCollectorTest.php

Add WebView, Asset collectors

---

src/Collector/EventCollector.php
tests/Collector/EventCollectorTest.php
tests/Support/DummyEvent.php

Collect event filename

---

src/Proxy/ProxyLogTrait.php

| Fixed issues  | https://github.com/yiisoft/proxy/issues/20
> :warning: Depends on PR https://github.com/yiisoft/proxy/pull/21.

Sync changes with proxy

---

.github/workflows/build.yml
composer.json
src/Proxy/ContainerInterfaceProxy.php
src/Proxy/LoggerInterfaceProxy.php

Update `psr/log` version

---

src/Proxy/ServiceMethodProxy.php
src/Proxy/ServiceProxy.php

| Fixed issues  | https://github.com/yiisoft/proxy/pull/39

Sync the latest changes with proxy

---

composer.json

Use stable version of `yiisoft/proxy` package

---

composer.json

Add `yiisoft/view` `^5.0` version support

---

config/params.php
src/Collector/ValidatorInterfaceProxy.php

Fix namespaces

---

composer.json

Add `yiisoft/view` version `^6.0` support

---

src/Collector/ValidatorInterfaceProxy.php

Adjust to `yiisoft/validator` changes

---

src/Collector/ValidatorCollector.php
src/Collector/ValidatorInterfaceProxy.php
tests/Collector/ValidatorCollectorTest.php

Fix validator collector

---

composer.json

Remove cache dependency

---

composer.json
config/params.php
src/Collector/QueueCollector.php
src/Collector/QueueDecorator.php
src/Collector/QueueFactoryInterfaceProxy.php
src/Collector/QueueWorkerInterfaceProxy.php
tests/Collector/QueueCollectorTest.php
tests/Collector/QueueDecoratorTest.php
tests/Support/DummyQueue.php

Add queue collector

---

src/Collector/QueueDecorator.php
tests/Support/DummyQueue.php

Fix queue decorator

---

src/Collector/QueueWorkerInterfaceProxy.php

Fix queue worker

---

src/Collector/CollectorTrait.php
src/Storage/FileStorage.php
tests/Collector/CollectorTestCase.php

Add collectors to index

---

src/Collector/ValidatorInterfaceProxy.php

Adopt validator changes

---

.editorconfig
src/Collector/ValidatorInterfaceProxy.php
tests/Collector/ValidatorInterfaceProxyTest.php

Adapt to last changes in `yiisoft/validator`

---

src/Collector/ValidatorInterfaceProxy.php

Adapt to validator changes

---

composer.json
src/Collector/RequestCollector.php
tests/Collector/RequestCollectorTest.php

Serialize request with guzzle

---

tests/Collector/ValidatorInterfaceProxyTest.php

Adapt to last changes in validator

---

src/Debugger.php
tests/DebuggerTest.php

Fix flushing data

---

composer.json

Add support `5.0` version of `yiisoft/middleware-dispatcher`

---

.gitignore
composer.json
config/common.php
src/Storage/FileStorage.php
src/Storage/MemoryStorage.php
tests/Storage/AbstractStorageTest.php
tests/Storage/FileStorageTest.php

Remove abstract FS

---

src/Collector/MiddlewareCollector.php
tests/Collector/MiddlewareCollectorTest.php

Fix MiddlewareCollector

---

tests/Collector/QueueCollectorTest.php
tests/Collector/ValidatorCollectorTest.php

Fix unit tests by syncing with validator changes

---

composer.json

Re-add `yiisoft/assets`:`^2.0` support

---

src/Helper/StreamWrapper/StreamWrapper.php

Fix stream wrapper return value

---

composer-require-checker.json
composer.json
config/params.php
src/Collector/AuthenticationMethodInterfaceProxy.php
src/Collector/IdentityCollector.php
tests/Collector/UserCollectorTest.php
tests/Support/FakeIdentity.php

Identities collector

---

composer.json
src/Collector/RouterCollector.php

Add current route to router collector

---

src/Collector/HttpClientCollector.php

Fix `HttpClientCollector`

---

src/Collector/QueueDecorator.php
tests/Support/DummyQueue.php

Adapt to last changes in `yiisoft/yii-queue`

---

composer.json
config/events-web.php
config/params.php
src/Collector/ExceptionCollector.php

Add exception collector

---

psalm.xml
src/Collector/Console/CommandCollector.php
src/Collector/HttpClientInterfaceProxy.php
src/Collector/Web/RequestCollector.php
src/Collector/Web/WebAppInfoCollector.php
tests/DumperTest.php

Psalm level 5

---

src/DebuggerIdGenerator.php

Remove dots from ID representation

---

src/Storage/FileStorage.php
src/Storage/MemoryStorage.php
src/Storage/StorageInterface.php
tests/Storage/AbstractStorageTest.php
tests/Storage/FileStorageTest.php

Optimize reading

---

src/Debugger.php
tests/Unit/DebuggerTest.php

Add ignore flags

---

tests/Unit/DumperTest.php

Should be merged after yiisoft/var-dumper release

Fix `var-dumper` test

---

docs/en/collector/http-client.md
docs/en/index.md

Add HttpClient collector docs

---

docs/en/collector/event-dispatcher.md
docs/en/collector/http-client.md
docs/en/index.md

Add Event collector docs

---

docs/en/collector/event-dispatcher.md
docs/en/collector/http-client.md
docs/en/collector/logger.md
docs/en/index.md

Add Log collector docs

---

psalm.xml
src/Collector/Console/CommandCollector.php
src/Collector/ContainerInterfaceProxy.php
src/Collector/EventDispatcherInterfaceProxy.php
src/Collector/HttpClientCollector.php
src/Collector/HttpClientInterfaceProxy.php
src/Collector/LoggerInterfaceProxy.php
src/Collector/Stream/HttpStreamProxy.php
src/Collector/VarDumperHandlerInterfaceProxy.php
src/Dumper.php
src/Helper/StreamWrapper/StreamWrapper.php
tests/Unit/Collector/ContainerInterfaceProxyTest.php
tests/Unit/Collector/LoggerInterfaceProxyTest.php

Increase psalm level to 3 and corresponding changes

---

src/Storage/FileStorage.php

Fix: getCollected to getSummary

---

config/params.php

Remove `MiddlewareCollector` usage

---

composer.json
src/Storage/FileStorage.php

Remove Yii JSON dependency

---

composer.json
config/di.php
tests/Unit/Storage/FileStorageTest.php

Remove `yiisoft/aliases` dependency

---

composer.json

Cleanup dependencies

---

src/Dumper.php
tests/Unit/DumperTest.php

Refactoring dumper (dump only arrays, mark as internal, simplification)

---

src/Dumper.php
tests/Unit/DumperTest.php

Remove closure from objects map

---

composer.json

Upgrade symfony/console: allow ^7.0
